version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:156962844638:task-definition/PMS-877629-eureka-server:2"
        LoadBalancerInfo:
          ContainerName: "eureka-server-container"
          ContainerPort: "8761"
        PlatformVersion: "LATEST"